"""fix transport table

Revision ID: 6b78ff14e185
Revises: e4dc1d116e91
Create Date: 2025-05-06 16:29:42.611284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b78ff14e185'
down_revision: Union[str, None] = 'e4dc1d116e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transport', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transport', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transport', type_='foreignkey')
    op.drop_column('transport', 'user_id')
    # ### end Alembic commands ###
